#!/bin/bash

if [[ "$#" -lt 1 || "$1" = "-h" ]] ; then
   echo "Usage: $(/usr/bin/basename $0) <input_file> [version] [nproc]"
   echo
   exit 1
fi

input=$1
version=$2
nproc=${NSLOTS}

#######LAUNCHING PROGRAM###########


source SetEnvironment.sh CP2K $version
if [[ $? != "0" ]];then
   echo "Error when exporting CP2K parameters in SetEnvironment.sh"
   exit 1
fi

DIR=$(pwd)
SCRDIR=/scratch/$USER/CP2K_${input}_${JOB_ID}

if [[ -d $SCRDIR ]];then
   echo "ERROR: scratch directory $SCRDIR already exist!"
   exit 1
fi

node=$(uname -n)
date
echo "NODE  $node" > job.log.${JOB_ID}
echo "SCRATCH  $SCRDIR" >> job.log.${JOB_ID}

mkdir $SCRDIR

coord_file=$(grep COORD_FILE_NAME $input | awk '{print $2}')
basis_file=$(grep BASIS_SET_FILE_NAME $input | awk '{print $2}')
corepot_file=$(grep POTENTIAL_FILE_NAME $input | awk '{print $2}')

cp -f $DIR/$input $DIR/$coord_file $DIR/$basis_file $DIR/$corepot_file $SCRDIR
cd $SCRDIR

if [[ $nproc -gt 1 ]];then
   $MPIRUN -np $nproc $CP2KEXE_MPI $input > $DIR/$input.out
else
   $CP2KEXE $input > $DIR/$input.out
fi

cd ../

cp -pr $SCRDIR $DIR

if [[ $? -ne "0" ]];then
  echo "Error when copying the data from scratch back to the server."
  echo "I will keep the directory $SCRDIR on node:"
  uname -a
  exit 1
fi

rm -r $SCRDIR

