#!/bin/bash

input=$1
version=$2
nproc=${NSLOTS}

#######LAUNCHING PROGRAM###########


source SetEnvironment.sh CP2K $version
if [[ $? != "0" ]];then
   echo "Error when exporting CP2K parameters in SetEnvironment.sh"
   exit 1
fi

DIR=$(pwd)
SCRDIR=/scratch/$USER/CP2K_$input_${JOB_ID}

if [[ -d $SCRDIR ]];then
   echo "ERROR: scratch directory $SCRDIR already exist!"
   exit 1
fi

mkdir $SCRDIR
cp $DIR/* $SCRDIR
cd $SCRDIR

if [[ $proc -gt 1 ]];then
   $MPIRUN -np $nproc $CP2KEXE_MPI $input > $DIR/$input.out
else
   $CP2KEXE $input > $DIR/$input.out
fi

cp -up * $DIR

if [[ $? -ne "0" ]];then
  echo "Error when copying the data from scratch back to the server."
  echo "I will keep the directory $SCRDIR on node:"
  uname -a
  exit 1
fi

cd ../
rm -r $SCRDIR

