#!/bin/bash

# Gaussian 2009 SGE submission script

#$ -V

# Set g09root based on the indentity of the cluster
source SetEnvironment.sh G09

input=$1
export scrhome="/scratch/$USER/"
export GAUSS_EXEDIR="$g09root"
export GAUSS_SCRDIR="/scratch/$USER/G09_$1_${JOB_ID}"
export LD_LIBRARY_PATH=$GAUSS_EXEDIR

if [ -e "$1" ]
then
 mkdir -p $GAUSS_SCRDIR
 echo "Running G09 job $1"
 uname -n
 date
 $GAUSS_EXEDIR/g09 $1 
else
 echo "`basename $0` input file does not exist."
fi

/bin/rm -rf /$GAUSS_SCRDIR
/bin/rm -rf ${scrhome}/*.rwf #u velkych vypoctu chceme umet restartovat z vln. fce,comment this
/bin/rm -rf ${scrhome}/*.scr
/bin/rm -rf core

