#!/bin/bash

# Gaussian 2009 SGE submission script

#$ -V
input=$1
version=$2

# Set gaussroot based on the indentity of the cluster
source SetEnvironment.sh GAUSSIAN $2
if [[ $? != "0" ]];then
   echo "Error when exporting Gaussian parameters in SetEnvironment.sh"
   exit 1
fi

export scrhome="/scratch/$USER/"
export GAUSS_EXEDIR="$gaussroot"
export GAUSS_SCRDIR="/scratch/$USER/GAUSS_$1_${JOB_ID}"
export LD_LIBRARY_PATH=$GAUSS_EXEDIR

if [ -e "$1" ]
then
 mkdir -p $GAUSS_SCRDIR
 echo "Running Gaussian job $1"
 uname -n
 date
 $GAUSSEXE $1
else
 echo "`basename $0` input file does not exist."
fi

function clean_scr {
   echo "Cleaning up temporary files."
   /bin/rm -rf /$GAUSS_SCRDIR
   /bin/rm -rf ${scrhome}/*.rwf #u velkych vypoctu chceme umet restartovat z vln. fce,comment this
   /bin/rm -rf ${scrhome}/*.scr
   /bin/rm -rf core
   exit
}


trap clean_scr EXIT
# The following should trap signal sent by qdel when submitted with qsub -notify option
# For unknown reason, this does not work
trap clean_scr SIGUSR2

