#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchG09 input.com queue' "
   exit 1
}

if [[ $# -lt "2" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

input=$1
queue=$2

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

PWD=$(pwd)

# Automatically determine number of processors
nproc=`grep proc $input  | head -1 | awk -F "=" '{if($2!=""){printf"%i",$2}}'`
 if [[ $nproc == "" ]];then
	 # we should ideally use regural expression, but NAH
nproc=`grep Proc $input  | head -1 | awk -F "=" '{if($2!=""){printf"%i",$2}}'`
 fi
 if [[ $nproc == "" ]];then
	 echo "Error: Could not determine the number of processors."
	 echo "Please set Nprocshared=x in Gaussian input file."
	 exit 1
 fi


cat > r.$input << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

G09 $input
EOF

echo "Launching G09 job."
echo "$nproc proccesors will be used." 


echo "qsub -cwd -q $queue -pe shm $nproc r.$input"
qsub -cwd -q $queue -pe shm $nproc r.$input

