#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchGAUSS input.com queue [-v version]' "
   echo " "
   . SetEnvironment.sh GAUSSIAN -ver
   exit 1
}

NUMPARAMS=2
index=0
while [[ $# > 0 ]]
do
   arg="$1"
   case $arg in
      "-h" )
      PrintHelp
      ;;
      "-v" )
      version=$2
      shift 
      ;;
      *)
      if [[ $index -eq 0 ]];then
         input=$1
      elif [[ $index -eq 1 ]];then
         queue=$1
      fi
      let index++
      ;;
   esac

   shift 

done

if [[ $index -ne $NUMPARAMS ]];then
   echo "Incorrect number of parameters."
   PrintHelp
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

PWD=$(pwd)

# Automatically determine number of processors
nproc=`egrep -i ^%nproc $input  | head -1 | awk -F "=" '{if($2!=""){printf"%i",$2}}'`
if [[ $nproc == "" ]];then
   echo "Error: Could not determine the number of processors."
   echo "Please set NprocShared=x in Gaussian input file."
   exit 1
fi

name=$(basename $input .inp)
name=$(basename $name .com)

cat > r.$name << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V
#$ -notify

GAUSS $input $version
EOF

echo "Launching Gaussian 09 job."
echo "$nproc proccesors will be used." 


echo "qsub -cwd -q $queue -pe shm $nproc r.$name"
qsub -cwd -q $queue -pe shm $nproc r.$name

