#!/bin/bash

function PrintHelp {
   echo " "
   echo "USAGE: 'launchQCHEM input.com queue [mpi|openmp] [nproc] [version]' "
   echo "(if you need non-default version, you must specify paralellization as well)"
   exit 1
}

#- Check input sanity ------

if [[ $# -lt "2" ]] || [[ "$1" = "-h" ]]; then
   PrintHelp
fi

input=$1
queue=$2
version=$5
para_type=openmp
nproc=1

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

if [[ ! -z $3 ]];then

  if [[ "$3" = "mpi" ]];then
     para_type=mpi
  elif [[ "$3" = "openmp" ]];then
     para_type=openmp
  else
     echo "Error in the third parameter: $3."
     echo "It should be either \"mpi\" or \"openmp\"."
     echo "Check the QCHEM manual and decide which type of parallelization is necessary for your method. "
     PrintHelp
  fi

  if [[ -z $4 ]];then
     echo "Please, provide the number of processors."
     PrintHelp
  else
     nproc=$4
  fi

fi

if [[ $4 -eq 1 && $3 = "mpi" ]]; then
    echo "QCHEM will not run an MPI job on a single processor."
    PrintHelp
fi


#- Everything OK, let's go.

cat > r.$input << EOF
#$ -cwd
#$ -e .
#$ -o .
#$ -V

QCHEM $input $para_type $version
EOF


echo "Launching QCHEM job."
echo "$nproc proccesors will be used." 

if [[ $para_type = "openmp" ]];then
   para_type=shm
fi

echo "qsub -cwd -q $queue -pe $para_type $nproc r.$input"
qsub -cwd -q $queue -pe $para_type $nproc r.$input

