#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchCP2K your_input.inp queue [nproc]' "
   echo " "
   exit 1
}

#- Check input sanity ------

if [[ $# -lt "2" ]] || [[ "$1" =~ -h ]]; then
   PrintHelp
fi

input=$1
queue=$2
nproc=$3
if [[ -z $3 ]];then
   nproc=1
fi

if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

name=$(basename $1 .inp)
name=$(basename $name .com)

cat > r.$name << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

CP2K $input
EOF

echo "Launching CP2K job."
echo "$nproc proccesors will be used." 

echo "qsub -cwd -q $queue -pe mpi $nproc r.$name"
qsub -cwd -q $queue -pe mpi $nproc r.$name

