#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: '$0 input.com queue [number_of_cpus] [version]' "
   exit 1
}

if [[ $# -lt "2" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

input=$1
queue=$2

if [[ ! -z $3 ]];then
   nproc=$3
else
   nproc=1
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

PWD=$(pwd)

cat > r.$input << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V


MOLPRO $input $4
EOF

if [[ "nproc" -gt 1 ]];then
   echo "Submitting Molpro job for parallel execution in ${queue} queue with ${nproc} processes."
   echo "qsub -cwd -q $queue -pe mpi_alt $nproc r.$input"
   qsub -cwd -q $queue -pe mpi_alt $nproc r.$input
else
   echo "Launching single-processor Molpro job."
   echo "qsub -cwd -q $queue r.$input"
   qsub -cwd -q $queue r.$input
fi

