#!/bin/bash

function PrintHelp {
   echo " "
   echo "USAGE: 'launchQC input.com queue [mpi|shm] [nproc]' "
   exit 1
}

#- Check input sanity ------

if [[ $# -lt "2" ]] || [[ "$1" = "-h" ]]; then
   PrintHelp
fi

input=$1
queue=$2
para_type=shm
nproc=1

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

if [[ ! -z $3 ]];then

  if [[ "$3" = "mpi" ]];then
     para_type=mpi
  elif [[ "$3" = "shm" ]];then
     para_type=shm
  else
     echo "Error in the third parameter: $3."
     echo "It should be either \"mpi\" or \"shm\"."
     PrintHelp
  fi

  if [[ -z $4 ]];then
     echo "Please, provide the number of processors."
     PrintHelp
  else
     nproc=$4
  fi

fi

if [[ $4 -eq 1 && $3 = "mpi" ]]; then
    echo "QCHEM will not run an MPI job on a single processor."
    PrintHelp
fi


#- Everything OK, let's go.

cat > r.$input << EOF
#$ -cwd
#$ -e .
#$ -o .
#$ -V

QCHEM $input $para_type
EOF


echo "Launching QCHEM job."
echo "$nproc proccesors will be used." 

echo "qsub -cwd -q $queue -pe $para_type $nproc r.$input"
qsub -cwd -q $queue -pe $para_type $nproc r.$input

