#!/bin/bash

function PrintHelp {
   echo " "
   echo "USAGE: 'launchQCHEM input.com queue [-p mpi|openmp] [-n nproc] [-v version]' "
   echo "where \"openmp\" or \"mpi\" id the type of parallelization used."
   echo "default is \"openmp\". See QCHEM manual for details."
   echo "MPI parallelization is not supported in version 4.3"
   . SetEnvironment.sh QCHEM -ver
   exit 1
}

NUMPARAMS=2

para_type=openmp
nproc=1

index=0
while [[ $# > 0 ]]
do
   arg="$1"
   case $arg in
      "-h" )
      PrintHelp
      ;;
      "-v" )
      version=$2
      shift 
      ;;
      "-n" )
      nproc=$2
      shift 
      ;;
      "-p" )
      para_type=$2
      if [[ $2 != "openmp" && $2 != "mpi" ]];then
         echo "Invalid parameter $2"
         PrintHelp
      fi
      shift 
      ;;
      *)
      if [[ $index -eq 0 ]];then
         input=$1
      elif [[ $index -eq 1 ]];then
         queue=$1
      fi
      let index++
      ;;
   esac

   shift 

done

if [[ $index -ne $NUMPARAMS ]];then
   echo $index
   echo "Incorrect number of parameters."
   PrintHelp
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

if [[ $nproc -eq 1 && $para_type = "mpi" ]]; then
    echo "QCHEM will not run an MPI job on a single processor."
    PrintHelp
fi


name=$(basename $input .inp)
name=$(basename $name .com)

cat > r.$name << EOF
#$ -cwd
#$ -e .
#$ -o .
#$ -V

QCHEM $input $version $para_type
EOF


echo "Launching QCHEM job."
echo "$nproc proccesors will be used." 

if [[ $para_type = "openmp" ]];then
   para_type=shm
fi

echo "qsub -cwd -q $queue -pe $para_type $nproc r.$name"
qsub -cwd -q $queue -pe $para_type $nproc r.$name

