#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchCP2K your_input.inp queue [-n nproc] [-v version]' "
   echo " "
   . SetEnvironment.sh CP2K -ver
   exit 1
}

NUMPARAMS=2
nproc=1
index=0
while [[ $# > 0 ]]
do
   arg="$1"
   case $arg in
      "-h" )
      PrintHelp
      ;;
      "-v" )
      version=$2
      shift 
      ;;
      "-n" )
      version=$2
      shift 
      ;;
      *)
      if [[ $index -eq 0 ]];then
         input=$1
      elif [[ $index -eq 1 ]];then
         queue=$1
      fi
      let index++
      ;;
   esac

   shift 

done
if [[ $index -ne $NUMPARAMS ]];then
   echo "Incorrect number of parameters."
   PrintHelp
fi

if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

name=$(basename $input .inp)
name=$(basename $name .com)

cat > r.$name << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

CP2K $input $version
EOF

echo "Launching CP2K job."
echo "$nproc proccesors will be used." 

echo "qsub -cwd -q $queue -pe mpi $nproc r.$name"
qsub -cwd -q $queue -pe mpi $nproc r.$name

