#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchORCA input.com queue' "
   exit 1
}

if [[ $# -lt "2" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

input=$1
queue=$2

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

nproc=$(grep 'PAL' $1 | awk -F "[#PAL]" '{print $4}')

if [[ $nproc == "" ]];then
   nproc=$(grep 'nprocs' $1 | awk -F "[#,nprocs]" '{print $4}')
fi

if [[ $nproc == "" ]];then
   nproc=1
fi

if [[ $nproc -gt 1 ]];then
   echo "Warning: parallel version of ORCA was not extensively tested."
   echo "You should first try whether you get the same results both with serial and parallel versions."
fi


cat >r.$1 << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

ORCA $input
EOF

echo "$nproc proccesors will be used" 
echo "qsub -cwd  -q $queue -pe mpi_alt $nproc r.$input"
qsub -cwd -q $queue -pe mpi_alt $nproc r.$input

