#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchG09 input.com queue' "
   exit 1
}

if [[ $# -lt "2" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

input=$1
queue=$2

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

PWD=$(pwd)

# Automatically determine number of processors
nproc=`egrep -i ^%nproc $input  | head -1 | awk -F "=" '{if($2!=""){printf"%i",$2}}'`
if [[ $nproc == "" ]];then
   echo "Error: Could not determine the number of processors."
   echo "Please set NprocShared=x in Gaussian input file."
   exit 1
fi


cat > r.$input << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

GAUSS $input
EOF

echo "Launching Gaussian 09 job."
echo "$nproc proccesors will be used." 


echo "qsub -cwd -q $queue -pe shm $nproc r.$input"
qsub -cwd -q $queue -pe shm $nproc r.$input

