#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchNWCHEM input.com queue [-n num_cpus] [-v version]' "
   echo " "
   . SetEnvironment.sh NWCHEM -ver
   exit 1
}
NUMPARAMS=2
nproc=1
index=0
while [[ $# > 0 ]]
do
   arg="$1"
   case $arg in
      "-h" )
      PrintHelp
      ;;
      "-v" )
      version=$2
      shift 
      ;;
      "-n" )
      version=$2
      shift 
      ;;
      *)
      if [[ $index -eq 0 ]];then
         input=$1
      elif [[ $index -eq 1 ]];then
         queue=$1
      fi
      let index++
      ;;
   esac

   shift 

done
if [[ $index -ne $NUMPARAMS ]];then
   echo "Incorrect number of parameters."
   PrintHelp
fi

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

name=$(basename $input .inp)
name=$(basename $name .com)

cat > r.$name << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

NWCHEM $input $nproc $version
EOF

if [[ "nproc" -gt 1 ]];then
   echo "Submitting Nwchem job for parallel execution in ${queue} queue with ${ncpus} processes."
   echo "qsub -cwd -q $queue -pe mpi_alt $nproc r.$name"
   qsub -cwd -q $queue -pe mpi_alt $nproc r.$name
else
   echo "Launching single-processor Nwchem job."
   echo "qsub -cwd -q $queue r.$name"
   qsub -cwd -q $queue r.$name
fi

