#!/bin/bash
function PrintHelp {
   echo " "
   echo "USAGE: 'launchORCA input.com queue' "
   exit 1
}

if [[ $# -lt "2" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

input=$1
queue=$2

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

# Assuming the comment is not closed by second #
#nproc=$(awk -F [#] '{print $1}' | egrep '! *PAL[2-8]' | awk -F "PAL" '{print $2}'  )
nproc=$(awk -F "#" '{print $1}'  $input | egrep -i '! *PAL[2-8]' | awk -F "PAL" '{print $2}' | awk '{print $1}')

# There is also the second possible syntax
if [[ $nproc = "" ]];then
   nproc=$(awk -F "#" '{print $1}'  $input | egrep -i 'nprocs' | awk -F "nprocs *=* *" '{print $2}' | awk '{print $1}')
fi
if [[ $nproc = "" ]];then
   nproc=1
fi


if [[ $nproc -gt 1 ]];then
   echo "Warning: parallel version of ORCA was not extensively tested."
   echo "You should first try whether you get the same results both with serial and parallel versions."
fi


cat >r.$1 << EOF
#!/bin/bash

#$ -cwd
#$ -e .
#$ -o .
#$ -V

ORCA $input
EOF

echo "$nproc proccesors will be used" 
if [[ "$nproc" -eq 1 ]];then
   echo "qsub -cwd -q $queue r.$input"
   qsub -cwd -q $queue r.$input
else
   echo "qsub -cwd -q $queue -pe mpi_alt $nproc r.$input"
   qsub -cwd -q $queue -pe mpi_alt $nproc r.$input
fi

