#!/bin/bash
input=$1
version=$2
nproc=${NSLOTS}
source SetEnvironment.sh NWCHEM

scratch=/scratch/${USER}

export INPFILE=$input.$JOB_ID
export LOGFILE=$input.log
export OUTFILE=$input.out

input=$(basename $input .inp)
input=$(basename $input .com)


export SCRATCH=${scratch}/NWCHEM-$input-${JOB_ID}
export WORKDIR=$PWD
mkdir -p ${SCRATCH}

echo "NODE  $node" > job.log.${JOB_ID}
echo "SCRATCH  $SCRATCH" >> job.log.${JOB_ID}

cd ${WORKDIR}
echo "scratch_dir $SCRATCH" > $INPFILE
grep -v "scratch_dir" $input >> $INPFILE

if [[ "$nproc" -gt 1 ]];then

   $MPIRUN -np $nproc $NWCHEMEXE $INPFILE 2>&1 > $INPFILE.out 

else

   $NWCHEMEXE $INPFILE 2>&1 > $INPFILE.out 

fi

rm -rf $SCRATCH
rm -rf core

