#!/bin/bash

#$ -cwd -V

#required libraries for OCTOPUS
source SetEnvironment.sh OCTOPUS

name=$1
jobfile=job.log
delscratch="true"

export basedir=$PWD
export scrdir="/scratch/${USER}"
export SCRATCH=$scrdir/${JOB_ID}

echo "NODE  ${HOSTNAME}"   >>  $jobfile
echo "SCRATCH  ${SCRATCH}"    >>  $jobfile
echo  $basedir      >>  $jobfile
echo 'NSLOTS: '${NSLOTS} >>  $jobfile   #NSLOTS

if [[ -d $SCRATCH ]];then
   echo "Job direcory $SCRDIR already exist!"
   echo "Exiting..."
   exit 1
else
   mkdir ${SCRATCH}
   cp -p * $SCRATCH/.
   if [[ -d static ]];then
      cp -r static $SCRATCH
   fi
   if [[ -d restart ]];then
      cp -r restart $SCRATCH
   fi
fi

cd $SCRATCH
 
function clean_scratch {
   echo "Job stopped after qdel ${JOB_ID}">> $jobfile
   echo "Copying current data back to $basedir/">> $jobfile
   cp -pr * $basedir/.
   cd ../
   rm -r $SCRATCH
   exit 1
}
trap clean_scratch SIGUSR2  #if qdel JOBID then copy current data to basedir


if [[ ${NSLOTS} -gt "1" ]]; then
mpirun -np ${NSLOTS} octopus > $name.out
else
octopus > $name.out
fi

echo 'Normal termination of:' ${JOB_ID} >> $jobfile
cp -pr * $basedir/.

if [[ $delscratch -eq "true" ]];then
  cd ../
  rm -r $SCRATCH
fi
