#!/bin/bash

input=$1
version=$2
# Also sets the MPI environment
source SetEnvironment.sh ORCA $version
if [[ $? != "0" ]];then
   echo "Error when exporting ORCA parameters in SetEnvironment.sh"
   exit 1
fi

KDE=$(pwd)

export PATH=$orcaroot:$PATH

# DH: I have no idea why this bit was here.
# ORCA appears to work without it.
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/programs/common/intel/compiler/2011.5.220/composerxe-2011.5.220/compiler/lib/intel64/

export SCRDIR="/scratch/$USER/ORCA_$1_${JOB_ID}"

mkdir -p $SCRDIR
cp $1 $SCRDIR
cd $SCRDIR
echo "Running ORCA job $1"
uname -n
date
$ORCAEXE $1 &> $KDE/$1.out 
/bin/rm -rf *.tmp*
cp * $KDE
if [[ $? -ne "0" ]];then
   echo "Error when copying the data from scratch back to the server."
   echo "I will keep the directory $SCRDIR on node:"
   uname -a
   exit 1
fi
cd ../
/bin/rm -rf $SCRDIR


