#!/bin/bash

# Script far running QCHEM calculations
# Serial mode or using parallel OpenMP.
# For parallel MPI version, the second parametr must be "mpi".
# Different methods are parallelized with OpenMP or MPI. See the manual.

if [ "$#" -lt 1 ] ; then
   echo "Usage: $(/usr/bin/basename $0) <input_file>"
   echo
   exit 1
fi

source SetEnvironment.sh QCHEM


export JOBDIR=$(pwd)
export INPUT=$1

export QCSCRATCH=${JOBDIR}
export QCLOCALSCR=/scratch/${USER}

if [[ ${NSLOTS} -eq 1 ]]; then
  source ${qcroot}/qcenv.sh

  qchem ${INPUT} ${INPUT}.out &> ${INPUT}.log

elif [[ $2 = "mpi" ]];then

  source $mpiset
  source ${qc_mpiroot}/qcenv.sh
  qchem -np ${NSLOTS} ${INPUT} ${INPUT}.out &> ${INPUT}.log

else

  source ${qcroot}/qcenv.sh
  qchem -nt ${NSLOTS} ${INPUT} ${INPUT}.out &> ${INPUT}.log

fi

rm -rf TMP core

